# ---------------------------------------------------------
# mode:
# CLASSIC         - Break logs above the log you broke
# CLASSIC_LEAVES  - CLASSIC plus breaks all leaves
# FULL            - Breaks all logs and leaves
# FULL_NOLEAVES   - Breaks all logs
# ---------------------------------------------------------
# enchantments:
# false - Tool enchantments don't affect broken blocks
# true  - Tool enchantments affect broken blocks
# ---------------------------------------------------------

mode: FULL
enchantments: false
logs:
- ACACIA_LOG
- BIRCH_LOG
- DARK_OAK_LOG
- JUNGLE_LOG
- OAK_LOG
- SPRUCE_LOG
leaves:
- ACACIA_LEAVES
- BIRCH_LEAVES
- DARK_OAK_LEAVES
- JUNGLE_LEAVES
- OAK_LEAVES
- SPRUCE_LEAVES
tools:
- DIAMOND_AXE
- GOLDEN_AXE
- IRON_AXE
- NETHERITE_AXE
- STONE_AXE
- WOODEN_AXE
